version: '2'

services:
  jsreport:
    image: jsreport/jsreport
    container_name: jsreport
    hostname: jsreport
    ports:
      - 5488:5488
  consul:
    image: consul
    container_name: consul
    network_mode: host
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    network_mode: host
  mongo:
    image: mongo
    container_name: mongo
    network_mode: host
  kafkaserver:
    image: "spotify/kafka:latest"
    container_name: kafka
    hostname: localhost
    network_mode: host
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      ADVERTISED_HOST: localhost
      ADVERTISED_PORT: 9092
  kafka_manager:
    image: "mzagar/kafka-manager-docker:1.3.3.4"
    container_name: kafkamanager
    network_mode: host
    ports:
      - 9000:9000
    environment:
      ZK_HOSTS: "localhost:2181"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
        - 9200:9200
  mn-documents-service:
    build: ./documents-service
    image: mn-documents-service
    container_name: mn-documents-service
    network_mode: host
  mn-policy-service:
    build: ./policy-service
    image: mn-policy-service
    container_name: mn-policy-service
    network_mode: host
  mn-policy-search-service:
    build: ./policy-search-service
    image: mn-policy-search-service
    container_name: mn-policy-search-service
    network_mode: host
  mn-pricing-service:
    build: ./pricing-service
    image: mn-pricing-service
    container_name: mn-pricing-service
    network_mode: host
  mn-payment-service:
    build: ./payment-service
    image: mn-payment-service
    container_name: mn-payment-service
    network_mode: host
  mn-product-service:
    build: ./product-service
    image: mn-product-service
    container_name: mn-product-service
    network_mode: host
  mn-auth-service:
    build: ./auth-service
    image: mn-auth-service
    container_name: mn-auth-service
    network_mode: host
  mn-chat-service:
    build: ./chat-service
    image: mn-chat-service
    container_name: mn-chat-service
    network_mode: host
  mn-dashboard-service:
    build: ./dashboard-service
    image: mn-dashboard-service
    container_name: mn-dashboard-service
    network_mode: host
  mn-agent-portal-gateway:
    build: ./agent-portal-gateway
    image: mn-agent-portal-gateway
    container_name: mn-agent-portal-gateway
    network_mode: host
  mn-web-vue:
    build: ./web-vue
    image: mn-web-vue
    container_name: mn-web-vue
    network_mode: host
