kind: Deployment
apiVersion: apps/v1
metadata:
  name: web-vue
  labels:
    app: web-vue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-vue
  template:
    metadata:
      labels:
        app: web-vue
    spec:
      containers:
      - name: web-vue
        image: ascmn/web-vue:latest
        env:
        - name: GATEWAY_URL
          value: "http://agent-portal-gateway"
        - name: AUTH_URL
          value: "http://auth-service"
        - name: CHAT_SERVICE_URL
          value: "http://chat-service"
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 1
          timeoutSeconds: 1
          periodSeconds: 1
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 5