micronaut:
  application:
    name: product-service
  server:
    host: localhost
    port: ${SERVICE_PORT:-1}
#  metrics:
#    enabled: true
---
#endpoints:
#  health:
#    enabled: true
#    sensitive: false
#  metrics:
#    enabled: true
#    sensitive: false
---
mongodb:
    uri: "mongodb://${MG_HOST:localhost}:${MG_PORT:27017}/demo"
    cluster:
      maxWaitQueueSize: 5
    connectionPool:
      maxSize: 20
---
consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
---
tracing:
  zipkin:
    enabled: true
    http:
      url: "http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}"
      sampler:
        probability: 1.0 # Configuration taking 100% of the request to be processed by Zipkin. In a real production system, that could be overwhelming.

