kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-server
  labels:
    srv: kafka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      srv: kafka-server
  template:
    metadata:
      labels:
        srv: kafka-server
    spec:
      hostname: kafka-server
      containers:
      - name: kafka-server
        image: bitnami/kafka:2.0.0
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        ports:
        - containerPort: 9092
        readinessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 3
          timeoutSeconds: 1
          periodSeconds: 1
        livenessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 5