kind: Deployment
apiVersion: apps/v1
metadata:
  name: chat-service
  labels:
    srv: chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      srv: chat-service
  template:
    metadata:
      labels:
        srv: chat-service
    spec:
      containers:
      - name: chat-service
        image: ascmn/chat-service:latest
        ports:
        - containerPort: 80
        env:
        - name: SERVICE_PORT
          value: "80"
        - name: ZIPKIN_HOST
          value: zipkin
        - name: ZIPKIN_PORT
          value: "9411"
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 3
          timeoutSeconds: 1
          periodSeconds: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 5